FROM python:3.3.6
MAINTAINER Will Liu "william.q.liu@gmail.com"
RUN apt-get update -y
RUN apt-get install -y vim python-pip python-dev build-essential
#WORKDIR /web
#RUN pip install -r requirements.txt
#WORKDIR /web/hipflask


