version: '2'
services:
  web:
    restart: always
    build:  # configuration options applied at build time
      context: ./web
      dockerfile: ./Dockerfile
    links:  # links to containers in another service
      - postgres:postgres
    env_file: .env
    volumes:
      - /usr/src/app/static
      - ./web:/web
    ports:  # map ports to a host:container format
      - "5000:5000"
    command: /usr/local/bin/uwsgi --ini /web/uwsgi.ini
    #command: uwsgi --http-socket :5000 --file /app/hipflask.py --protocol=http

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    links:
      - web:web
    ports:
      - "80:80"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
