version: '2'
services:

  web:
    restart: always
    env_file: .env
    links:  # links to containers in another service
      - postgres
      - redis
    build:  # configuration options applied at build time
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - /usr/src/app/static
      - ./web:/web
    expose:
      - "5000"
    depends_on:
      - postgres
    command: sh /web/scripts/post-run.sh

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    links:
      - web
    volumes:
      - /www/static
    ports:  # map ports to a host:container format
      - "80:80"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:3.0.7
    ports:
      - "6379:6379"
